version: '3.8'
services:
  alice.node:
    container_name: "${APP_CONTAINER_PREFIX}_node"
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    working_dir: ${WORKING_DIR}
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend

  alice.nginx:
    container_name: "${APP_CONTAINER_PREFIX}_nginx"
    image: nginx
    ports:
      - "${NGINX_PORT}:80"
      # - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./:${WORKING_DIR}
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/letsencrypt
      - ./docker/nginx/certs-data:/data/letsencrypt
    restart: always
    depends_on:
      - alice.node
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - web
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./docker/nginx/certs:/etc/letsencrypt
      - ./docker/nginx/certs-data:/data/letsencrypt
    entrypoint: "/bin/sh -c"
    command: >
      trap exit TERM;
      while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /data/letsencrypt && nginx -s reload; done
    depends_on:
      - alice.nginx
    networks:
      - web

volumes:
  certs:
  certs-data:

networks:
  web:
    driver: bridge
  backend:
    driver: bridge
